# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5d05ba0ea4348ac0b06191012f5b4091"
name = "ugc-acumen"
handle = "ugc-acumen"
application_url = "https://ugc.acumen-camera.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://ugc.acumen-camera.com/auth/callback", "https://ugc.acumen-camera.com/auth/shopify/callback", "https://ugc.acumen-camera.com/api/auth/callback"]

[pos]
embedded = false

[app_proxy]
prefix = "apps"
subpath = "ugc-acumen"
url = "https://ugc.acumen-camera.com"
